from adya.common.constants import action_constants

actions = [
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.TRANSFER_OWNERSHIP, "name":"Transfer Ownership", "description":"Transfer ownership of all documents owned by \"{{full_name}}\"", "parameters":[{"key": "old_owner_email", "label": "OldUser", "editable": 0}, {"key": "new_owner_email", "label": "NewUser", "editable": 1}], "is_admin_only":True},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.CHANGE_OWNER_OF_FILE, "name":"Transfer Ownership", "description":"Transfer ownership of \"{{resource_name}}\"", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}, {"key": "old_owner_email", "label": "OldUser", "editable": 0}, {"key": "new_owner_email", "label": "NewUser", "editable": 1}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.REMOVE_EXTERNAL_ACCESS, "name":"Remove external sharing","description":"Remove access from outside the company for all documents owned by \"{{full_name}}\"", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.REMOVE_EXTERNAL_ACCESS_TO_RESOURCE, "name":"Remove external sharing", "description":"Remove access from outside the company for \"{{resource_name}}\"", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.MAKE_ALL_FILES_PRIVATE, "name":"Remove all sharing", "description":"Remove access to everyone for all documents owned by \"{{full_name}}\"", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.MAKE_RESOURCE_PRIVATE, "name":"Remove all sharing", "description":"Remove access to everyone (except owner) for \"{{resource_name}}\"", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.DELETE_PERMISSION_FOR_USER, "name":"Remove sharing", "description":"Remove sharing of selected document with user", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}, {"key": "resource_owner_id", "label": "Owneroffile", "editable": 0}, {"key": "user_email", "label": "ForUser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.UPDATE_PERMISSION_FOR_USER, "name":"Change permission", "description":"Change permission for selected document with user", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}, {"key": "resource_owner_id", "label": "Owneroffile", "editable": 0}, {"key": "user_email", "label": "ForUser", "editable": 0}, {"key": "new_permission_role", "label": "Newpermission", "editable": 1}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.WATCH_ALL_ACTION_FOR_USER, "name":"Watch activity", "description":"Get weekly report of all activities for \"{{full_name}}\"", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.NOTIFY_USER_FOR_CLEANUP, "name":"Notify user", "description":"Send mail to \"{{full_name}}\" to audit documents", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"QUICK_ACTION", "action_entity":"USER", "key":action_constants.ActionNames.REMOVE_ALL_ACCESS_FOR_USER, "name":"Remove access", "description":"Remove access to \"{{full_name}}\" for any documents owned by others", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.REMOVE_USER_FROM_GROUP, "name":"Change groups", "description":"Remove user from a group", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}, {"key": "group_email", "label": "ForGroup", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.ADD_USER_TO_GROUP, "name":"Change groups", "description":"Add user to a group", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}, {"key": "group_email", "label": "ForGroup", "editable": 1}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.ADD_PERMISSION_FOR_A_FILE, "name":"Add sharing", "description":"Share the selected resource with user", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 1}, {"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}, {"key": "new_permission_role", "label": "Newpermission", "editable": 0}, {"key": "resource_owner_id", "label": "Owneroffile", "editable": 0}, {"key": "user_type", "label": "UserType", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"GSUITE", "action_type":"INLINE", "action_entity":"APP", "key":action_constants.ActionNames.REMOVE_USER_FROM_APP, "name":"Uninstall app", "description":"Uninstall app for user", "parameters":[{"key": "client_id", "label": "ClientId", "editable": 0, "hidden": 1}, {"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":True},
    {"datasource_type":"SLACK", "action_type":"QUICK_ACTION", "action_entity":"INTERNAL_USER", "key":action_constants.ActionNames.REMOVE_EXTERNAL_ACCESS, "name":"Remove external sharing","description":"Remove access from outside the company for all documents owned by \"{{full_name}}\"", "parameters":[{"key": "user_email", "label": "Foruser", "editable": 0}], "is_admin_only":False},
    {"datasource_type":"SLACK", "action_type":"QUICK_ACTION", "action_entity":"DOCUMENT", "key":action_constants.ActionNames.REMOVE_EXTERNAL_ACCESS_TO_RESOURCE, "name":"Remove external sharing", "description":"Remove access from outside the company for \"{{resource_name}}\"", "parameters":[{"key": "resource_id", "label": "Selecteddocument", "editable": 0, "hidden": 1}, {"key": "resource_name", "label": "Selecteddocument", "editable": 0}], "is_admin_only":False},
]
