export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';

export const DASHBOARD_PAGE_LOADED = 'DASHBOARD_PAGE_LOADED';
export const DASHBOARD_PAGE_UNLOADED = 'DASHBOARD_PAGE_UNLOADED';

export const DASHBOARD_WIDGET_LOAD_START = 'DASHBOARD_WIDGET_LOAD_START';
export const DASHBOARD_WIDGET_LOADED = 'DASHBOARD_WIDGET_LOADED';

export const USERS_PAGE_LOADED = 'USERS_PAGE_LOADED';
export const USERS_PAGE_UNLOADED = 'USERS_PAGE_UNLOADED';

export const RESOURCES_PAGE_LOADED = 'RESOURCES_PAGE_LOADED';
export const RESOURCES_PAGE_UNLOADED = 'RESOURCES_PAGE_UNLOADED';

export const REPORTS_PAGE_LOADED = 'REPORTS_PAGE_LOADED';
export const REPORTS_PAGE_UNLOADED = 'REPORTS_PAGE_UNLOADED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const SET_DATASOURCES = 'SET_DATASOURCES';
export const CREATE_DATASOURCE = 'CREATE_DATASOURCE';

export const API_ROOT = process.env.REACT_APP_API_ROOT || 'http://127.0.0.1:5000';