service: adya-google

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.stages.${self:provider.stage}.awsProfile}
  region: ${self:custom.stages.${self:provider.stage}.region}
  timeout: 300
  versionFunctions: false
  environment:
    UI_HOST: ${self:custom.stages.${self:provider.stage}.httpProtocol}${self:custom.stages.${self:provider.stage}.uiHost}
    API_HOST: ${self:custom.stages.${self:provider.stage}.httpProtocol}${self:custom.stages.${self:provider.stage}.apiHost}
    DB_URL: ${opt:DB_URL, 'localhost:3306'}
    DB_USERNAME: ${opt:DB_USERNAME, 'root'}
    DB_PWD: ${opt:DB_PWD, 'root'}
    DB_NAME: ${opt:DB_NAME, 'dev'}
    DEPLOYMENT_ENV: ${self:provider.stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "ses:SendEmail"
        - "lambda:InvokeFunction"
        - "lambda:GetFunction"
        - "events:PutRule"
        - "events:PutTargets"
        - "lambda:AddPermission"
        - "events:*"
        - "iam:PassRole"
        - "ses:SendRawEmail"
      Resource:
        "*"

plugins:
  - serverless-domain-manager

custom:
  defaultStage: dev
  stages:
    dev:
      awsProfile: devProfile
      dbName: "dev"
      region: us-east-1
      httpProtocol: "https://"
      apiHost: "api-dev.adyatest.com"
      uiHost: "app.adyatest.com"
    prod:
      awsProfile: prodProfile
      dbName: "prod"
      region: us-east-1
      httpProtocol: "https://"
      apiHost: "api.adya.io"
      uiHost: "app.adya.io"

  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.apiHost}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional

functions:
  get-googleoauthlogin:
    handler: adya.services.lambda.auth_handler.google_oauth_request
    events:
      - http:
          path: googleoauthlogin
          method: get

  get-googleoauthcallback:
    handler: adya.services.lambda.auth_handler.google_oauth_callback
    events:
      - http:
          path: googleoauthcallback
          method: get

  post-scan-start:
    handler: adya.services.lambda.scan_handler.start_scan
    events:
      - http:
          path: scan/start
          method: post
          cors: true

  get-scan-resources:
    handler: adya.services.lambda.scan_handler.get_drive_resources
    events:
      - http:
          path: scan/resources
          method: get
          cors: true

  post-scan-resources:
    handler: adya.services.lambda.scan_handler.process_drive_resources
    events:
      - http:
          path: scan/resources
          method: post
          cors: true

  post-scan-permisssions:
    handler: adya.services.lambda.scan_handler.process_resource_permissions
    events:
      - http:
          path: scan/permisssions
          method: post
          cors: true

  get-scan-domainusers:
    handler: adya.services.lambda.scan_handler.get_domain_users
    events:
      - http:
          path: scan/domainusers
          method: get
          cors: true

  post-scan-domainusers:
    handler: adya.services.lambda.scan_handler.process_domain_users
    events:
      - http:
          path: scan/domainusers
          method: post
          cors: true

  get-scan-domaingroups:
    handler: adya.services.lambda.scan_handler.get_domain_groups
    events:
      - http:
          path: scan/domaingroups
          method: get
          cors: true

  post-scan-domaingroups:
    handler: adya.services.lambda.scan_handler.process_domain_groups
    events:
      - http:
          path: scan/domaingroups
          method: post
          cors: true

  post-scan-usersapp:
    handler: adya.services.lambda.scan_handler.get_user_app
    events:
      - http:
          path: scan/usersapp
          method: post
          cors: true

  delete-scan-usersapp:
    handler: adya.services.lambda.scan_handler.revoke_user_app_access
    events:
      - http:
          path: scan/usersapp
          method: delete
          cors: true

  get-scan-groupmembers:
    handler: adya.services.lambda.scan_handler.get_group_members
    events:
      - http:
          path: scan/groupmembers
          method: post
          cors: true

  get-scan-handlechannelexpiration:
    handler: adya.services.lambda.scan_handler.handle_channel_expiration
    events:
      - http:
          path: handlechannelexpiration
          method: get
          cors: true

  post-scan-processnotifications:
    handler: adya.services.lambda.scan_handler.process_gdrive_notifications
    events:
      - http:
          path: scan/processnotifications
          method: post
          cors: true

  post-scan-subscribenotifications:
    handler: adya.services.lambda.scan_handler.subscribe_gdrive_notifications
    events:
      - http:
          path: scan/subscribenotifications
          method: post
          cors: true

  post-scan-processdirectorynotifications:
    handler: adya.services.lambda.scan_handler.process_directory_notification
    events:
      - http:
          path: scan/directoryprocessnotifications
          method: post
          cors: true