# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: adya

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.stages.${self:provider.stage}.awsProfile}
  region: ${self:custom.stages.${self:provider.stage}.region}
  timeout: 300
  environment:
    UI_HOST: ${self:custom.stages.${self:provider.stage}.uiHost}
    API_HOST: https://${self:custom.stages.${self:provider.stage}.apiHost}
    DB_URL: ${opt:DB_URL, 'localhost:3306'}
    DB_USERNAME: ${opt:DB_USERNAME, 'root'}
    DB_PWD: ${opt:DB_PWD, 'root'}
    DB_NAME: ${opt:DB_NAME, 'dev'}

plugins:
  - serverless-domain-manager

custom:
  defaultStage: dev
  stages:
    dev: 
      awsProfile: devProfile
      dbName: "dev"
      region: us-east-1
      apiHost: "api-dev.adyatest.com"
      uiHost: "https://app.adyatest.com"
    prod: 
      awsProfile: prodProfile
      dbName: "prod"
      region: us-east-1
      apiHost: "api.adya.io"
      uiHost: "https://app.adyatest.com"

  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.apiHost}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional


# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - api/datasources/**
#  exclude:
#    - lib/**
#    - exclude-me-dir/**

functions:
  googleoauthrequet:
    handler: adya.services.lambda.auth_handler.google_oauth_request
    events:
      - http:
          path: googleoauthlogin
          method: get

  googleoauthcallback:
    handler: adya.services.lambda.auth_handler.google_oauth_callback
    events:
      - http:
          path: googleoauthcallback
          method: get

  currentuser:
    handler: adya.services.lambda.auth_handler.current_user
    events:
      - http:
          path: user
          method: get
          cors: true

  getdatasource:
    handler: adya.services.lambda.domain_handler.get_datasource
    events:
      - http:
          path: datasources
          method: get
          cors: true

  postdatasource:
    handler: adya.services.lambda.domain_handler.post_datasource
    events:
      - http:
          path: datasources
          method: post
          cors: true

  getwidgetdata:
    handler: adya.services.lambda.reports_handler.get_widget_data
    events:
      - http:
          path: widgets
          method: get
          cors: true

  postscheduledreport:
    handler: adya.services.lambda.reports_handler.post_scheduled_report
    events:
      - http:
          path: reports
          method: post
          cors: true

